### ISSUE TITLE
migrateコマンドでエラーが出る

### ISSUE THREAD

**Issue by horsewin** [uma-arai/sbcntr-frontend#1]
## エラーログ
```sh
$ npm run migrate:dev

> sbcntr-frontend@1.0.0 migrate:dev /home/ec2-user/environment/sbcntr-frontend
> npx blitz prisma migrate dev --preview-feature

You are using beta software - if you have any problems, please open an issue here:
      https://github.com/blitz-js/blitz/issues/new/choose

Environment variables loaded from .env
Error: Unknown binaryTarget rhel-openssl-3.0.x and no custom binaries were provided
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sbcntr-frontend@1.0.0 migrate:dev: `npx blitz prisma migrate dev --preview-feature`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sbcntr-frontend@1.0.0 migrate:dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ec2-user/.npm/_logs/2024-03-06T13_30_09_238Z-debug.log
```
## 再現環境
```sh
$ npx blitz --version
You are using beta software - if you have any problems, please open an issue here:
      https://github.com/blitz-js/blitz/issues/new/choose

Linux 6.1 | linux-x64 | Node: v14.16.1

blitz: 0.33.1 (local)

  Package manager: yarn 
  System:
    OS: Linux 6.1 Amazon Linux 2023
    CPU: (2) x64 Intel(R) Xeon(R) Platinum 8259CL CPU @ 2.50GHz
    Memory: 185.37 MB / 7.63 GB
    Shell: 5.2.15 - /bin/bash
  Binaries:
    Node: 14.16.1 - ~/.nvm/versions/node/v14.16.1/bin/node
    Yarn: 1.22.21 - ~/.nvm/versions/node/v14.16.1/bin/yarn
    npm: 6.14.12 - ~/.nvm/versions/node/v14.16.1/bin/npm
    Watchman: Not Found
  npmPackages:
    @prisma/client: ~2.19 => 2.19.0 
    blitz: 0.33.1 => 0.33.1 
    prisma: ~2.19 => 2.19.0 
    react: 0.0.0-experimental-3310209d0 => 0.0.0-experimental-3310209d0 
    react-dom: 0.0.0-experimental-3310209d0 => 0.0.0-experimental-3310209d0 
    typescript: 4.1.2 => 4.1.2 
```

**Comment by horsewin** [comment]
PrismaのバージョンをOpenSSL3系が同梱されるものにあげるだけでいけそう。

```
diff --git a/package.json b/package.json
index ca27dc4..5b3880f 100644
--- a/package.json
+++ b/package.json
@@ -39,12 +39,12 @@
     "@material-ui/core": "4.11.3",
     "@material-ui/icons": "4.11.2",
     "@material-ui/lab": "4.0.0-alpha.57",
-    "@prisma/client": "~2.19",
+    "@prisma/client": "3.13.0",
     "blitz": "0.33.1",
     "final-form": "4.20.1",
     "isomorphic-unfetch": "3.1.0",
     "mui-rff": "3.0.3",
-    "prisma": "~2.19",
+    "prisma": "3.13.0",
     "react": "0.0.0-experimental-3310209d0",
     "react-dom": "0.0.0-experimental-3310209d0",
     "react-error-boundary": "3.1.0",
```

**Comment by shinakazu** [comment]
コメント失礼します。
本 issue の修正に伴い sbcntr-frontend コンテナが停止してしまう事象が発生しているように見受けられましたため、ご確認いただけますと幸いです。
なお、当該事象は main ブランチ (frontend からの DB 接続有) を利用した際に発生し、自分の環境で試した際は ECS Cluster 上でタスク実行を継続することができませんでした。

具体的には、本 issue の修正が含まれる [commit (ad475d6)](https://github.com/uma-arai/sbcntr-frontend/commit/ad475d6ebc965569eaca7f90a5828ebc2ff563e8) から作成した docker image を用いてコンテナを起動したところ、すぐに終了してしまうようでした。

一方で、本 issue の修正を含まない [commit (v1.0.0 : 1c13f7b)](https://github.com/uma-arai/sbcntr-frontend/commit/1c13f7b3363a0f30efef94e3dd3313e838bb9889) では、コンテナを起動し維持することが可能でした。

参考情報とはなりますが、上述の両コンテナについて自分のローカルの docker 環境で確認ができた log を添付します。
`Error: Cannot find module '/app/.next/prerender-manifest.json'` というエラーが発生したことにより、コンテナが終了してしまっているように見受けられます。

- 本 issue の修正が含まれる commit から作成したコンテナのログ
    ```bash
    $ docker logs fe-ad475d6

    > sbcntr-frontend@1.0.1 start:prd /app
    > npx blitz start --port 80

    You are using beta software - if you have any problems, please open an issue here:
        https://github.com/blitz-js/blitz/issues/new/choose

    > ⚠️  Git doesn't seem to be installed. Get it here: https://git-scm.com/downloads.
    ready - started server on 0.0.0.0:80, url: http://localhost:80
    info  - Loaded env from /app/.env
    warn  - You have enabled experimental feature(s).
    warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use them at your own risk.

    Error: Cannot find module '/app/.next/prerender-manifest.json'
    Require stack:
    - /app/node_modules/next/dist/next-server/server/next-server.js
    - /app/node_modules/next/dist/server/next.js
    - /app/node_modules/next/dist/server/lib/start-server.js
    - /app/node_modules/next/dist/cli/next-start.js
    - /app/node_modules/next/dist/bin/next
        at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
        at Function.mod._resolveFilename (/app/node_modules/next/dist/build/webpack/require-hook.js:4:1784)
        at Function.Module._load (internal/modules/cjs/loader.js:725:27)
        at Module.require (internal/modules/cjs/loader.js:952:19)
        at require (internal/modules/cjs/helpers.js:88:18)
        at Server.getPrerenderManifest (/app/node_modules/next/dist/next-server/server/next-server.js:36:318)
        at Server.getPreviewProps (/app/node_modules/next/dist/next-server/server/next-server.js:36:461)
        at new Server (/app/node_modules/next/dist/next-server/server/next-server.js:3:329)
        at NextServer.createServer (/app/node_modules/next/dist/server/next.js:1:2745)
        at /app/node_modules/next/dist/server/next.js:1:3143 {
    code: 'MODULE_NOT_FOUND',
    requireStack: [
        '/app/node_modules/next/dist/next-server/server/next-server.js',
        '/app/node_modules/next/dist/server/next.js',
        '/app/node_modules/next/dist/server/lib/start-server.js',
        '/app/node_modules/next/dist/cli/next-start.js',
        '/app/node_modules/next/dist/bin/next'
    ]
    }
    npm ERR! code ELIFECYCLE
    npm ERR! errno 1
    npm ERR! sbcntr-frontend@1.0.1 start:prd: `npx blitz start --port 80`
    npm ERR! Exit status 1
    npm ERR! 
    npm ERR! Failed at the sbcntr-frontend@1.0.1 start:prd script.
    npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

    npm ERR! A complete log of this run can be found in:
    npm ERR!     /root/.npm/_logs/2024-09-27T02_27_07_459Z-debug.log
    ```

- v1.0.0 (1c13f7b) より作成したコンテナのログ
    ```bash
    $ docker logs fe-1c13f7b

    > sbcntr-frontend@1.0.0 start:prd /app
    > npx blitz start --port 80

    You are using beta software - if you have any problems, please open an issue here:
        https://github.com/blitz-js/blitz/issues/new/choose

    > ⚠️  Git doesn't seem to be installed. Get it here: https://git-scm.com/downloads.
    ready - started server on 0.0.0.0:80, url: http://localhost:80
    info  - Loaded env from /app/.env
    warn  - You have enabled experimental feature(s).
    warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use them at your own risk.
    ```
